api/urls.py
from rest_framework import routers
from .views import TarefaViewSet
from django.urls import path, include

router = routers.DefaultRouter()
router.register("tarefas", TarefaViewSet)

app_name = "api"

urlpatterns = [
    path('', include(router.urls))
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tarefas.urls', namespace="tarefas")),
    path('api/', include('api.urls', namespace="api")),

]

tarefas/urls.py
from django.urls import path
from .views import list_tarefas, detalhes_tarefas, add_tarefas, edit_tarefas, deletar_tarefa


app_name = "tarefas"

urlpatterns = [
    path('', list_tarefas, name="list"),
    path('<int:tarefa_id>/detalhes/', detalhes_tarefas, name='detalhes'),
    path('inserir/', add_tarefas, name='inserir'),
    path("<int:tarefa_pk>/editar/", edit_tarefas, name="editar"),
    path("<int:tarefa_pk>/deletar", deletar_tarefa, name="delete"),
]

api/models.py
from django.db import models

# Create your models here.

tarefas/models.py
from django.db import models


class Tarefa(models.Model):
    TAREFA_STATUS = [
        ("concluido", "Concluído"),
        ("nao_concluido", "Não Concluído")
    ]
    titulo = models.CharField("Titulo", max_length=200)
    conteudo = models.TextField("Descrição")
    status = models.CharField("Status", default="nao_concluido", choices=TAREFA_STATUS, max_length=15)

tarefas/forms.py
from django import forms
from .models import Tarefa


class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = ("titulo", "conteudo", "status")

api/views.py
from rest_framework import viewsets
from tarefas.models import Tarefa
from .serializers import TarefaSerializer


class TarefaViewSet(viewsets.ModelViewSet):
    queryset = Tarefa.objects.all()
    serializer_class = TarefaSerializer

tarefas/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404

from .models import Tarefa
from .forms import TarefaForm


def list_tarefas(request):
    tarefas = Tarefa.objects.all()
    return render(request, 'tarefas/list.html', {'tarefas': tarefas})


def detalhes_tarefas(request, tarefa_id):
    tarefa = Tarefa.objects.get(id=tarefa_id)
    return render(request, 'tarefas/detalhes.html', {'tarefa': tarefa})


def add_tarefas(request):
    form = TarefaForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect(reverse("tarefas:list"))

    return render(request, "tarefas/add.html", context={"form": form})


def edit_tarefas(request, tarefa_pk):
    tarefa = get_object_or_404(Tarefa.objects, pk=tarefa_pk)
    form = TarefaForm(request.POST or None, instance=tarefa)

    if form.is_valid():
        form.save()
        return redirect(reverse("tarefas:list"))

    return render(request, "tarefas/edit.html", context={"tarefa": tarefa, "form": form})


def deletar_tarefa(request, tarefa_pk):
    tarefa = get_object_or_404(Tarefa.objects, pk=tarefa_pk)

    tarefa.delete()

    return redirect(reverse("tarefas:list"))

tarefas/templates/tarefas/add.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>To-Do-App</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'tarefas:list' %}" class="navbar-brand d-flex align-items-center">
                <strong>To-Do-App</strong>
            </a>
        </div>
    </div>
</head>

<body>

<main role="main" class="container">

    <div class="container">
        <form method=POST>
            {% csrf_token %}

            <label class="h4">Título</label>
            <input type="text" class="form-control" {{ form.titulo }}

            <label class="h4">Descrição</label>
            <input type="text" class="form-control" {{ form.conteudo }}

            <label class="h4">Status</label>
            <select type="text" class="form-control" {{ form.status }}

            <a href="{% url 'tarefas:inserir' %}" class="btn btn-primary my-2">
                <button style="border:0; background-color: transparent; color:white">Adicionar Tarefa</button>
            </a>
        </form>

    </div>

</main>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

tarefas/templates/tarefas/detalhes.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <h2>{{ tarefa.titulo }} - {{ tarefa.get_status_display }}</h2>
    </div>
    <div class="container">
        <h3> Descrição </h3>
    </div>
    <div class="container">
        <p>{{ tarefa.conteudo }}</p>
    </div>

{% endblock %}

tarefas/templates/tarefas/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>To-Do-App</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'tarefas:list' %}" class="navbar-brand d-flex align-items-center">
                <strong>To-Do-App</strong>
            </a>
        </div>
    </div>
</head>

<body>

<main role="main" class="container">

    <div class="container">
        <form method=POST>
            {% csrf_token %}

            <label class="h4">Título</label>
            <div><input type="text" class="form-control"{{ form.titulo }}</div>

            <label class="h4">Descrição</label>
            <textarea class="form-control" {{ form.conteudo }}

            <label class="h4">Status</label>
            <div><select type="text" class="form-control" {{ form.status }}</div>

                <a href="{% url 'tarefas:inserir' %}" class="btn btn-primary my-2">
                    <button style="border:0; background-color: transparent; color:white">Editar Tarefa</button>
                </a>
        </form>

    </div>

</main>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

tarefas/templates/tarefas/list.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
    {% for tarefa in tarefas%}
            <div class="container">

        <div class="row">
            <div class="col">
                <div class="card mb-4 shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="150"
                         aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title></title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ tarefa.titulo }}</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'tarefas:detalhes' tarefa.id %}"><button class="btn btn-sm btn-outline-secondary">Ver</button></a>
                                <a href="{% url 'tarefas:editar' tarefa.pk %}" ><button type="button" class="btn btn-sm btn-outline-secondary">Editar</button></a>
                                 <a href="{% url 'tarefas:delete' tarefa.pk %}" ><button type="button" class="btn btn-sm btn-outline-secondary">Excluir</button></a>
                            </div>
                            <p>{{ tarefa.get_status_display }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>To-Do-App</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'tarefas:list' %}" class="navbar-brand d-flex align-items-center">
                <strong>To-Do-App</strong>
            </a>
        </div>
    </div>

</head>
<body>


<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1>Minhas Tarefas</h1>
            <p class="lead text-muted">Aplicativo para cadastro de tarefas</p>
            <p>
                <a href="{% url 'tarefas:inserir' %}" class="btn btn-primary my-2">Inserir Tarefa</a>
            </p>
        </div>
    </section>




</main>

{% block content %}{% endblock %}

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Ir para o topo</a>
        </p>
        <p>Atividade realizada para avaliação do mini curso de Django e Django Rest Api</p>
        <p>Deseja ver o projeto na íntegra? <a href="https://github.com/">Visite o repositório.</a></p></p>
    </div>
</footer>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>